### ISSUE TITLE
DataCite schema may have attribute values without element values

### ISSUE THREAD

**Issue by amyehodge** [sul-metadata/stanford-library-metadata#15]
I noticed a little subtlety in the XML conversion for this just now.
 
In the DataCite schema, resourceTypeGeneral is required, but resourceType is not.
 
The spreadsheet I was converting did not have resourceType filled in initially. When converted to XML, the resourceTypeGeneral was left out as well. When I added in a resourceType, it was included as expected:
 
      <resourceType resourceTypeGeneral="Software">Research Tool</resourceType>
 
It would be nice if in the first case this had shown up as
 
      <resourceType resourceTypeGeneral="Software"> </resourceType>
 
which would have validated in the DataCite form. It would not validate without the resourceType field present and resourceTypeGeneral filled in.

**Comment by arcadiafalcone** [comment]
Closed via #52.
