### ISSUE TITLE
DataCite/MODS tool: not all hydrus roles available in template

### ISSUE THREAD

**Issue by amyehodge** [sul-metadata/stanford-library-metadata#42]
Today I needed "advisor" and "primary advisor" in order to match up with existing content on a PURL. When I added these by hand to the list in the template I could use them, but other fields were automatically populated with "0" which I had to modify by hand later. It would be nice to have these in the template and functioning properly, and anything else that is missing.

**Comment by arcadiafalcone** [comment]
Closed via #52.
