### ISSUE TITLE
DataCite/MODS tool: add relatedIdentifier information to DataCite xml output

### ISSUE THREAD

**Issue by amyehodge** [sul-metadata/stanford-library-metadata#47]
The current replayable spreadsheet for this includes the related publication information as a free text citation, but needs to include several fields for DataCite that include the related identifier, related identifier type, and relation type.  
 
The related publication information is important to include because it’s required for the Event Data that is generated that tracks links between papers (with DOIs) and datasets (with DOIs). I hope we'll be implementing this in the fall work cycle on SDR.
 
For the record, this is what I added by hand to the XML for the DOI I recently generated.
 
<relatedIdentifiers>
      <relatedIdentifier relatedIdentifierType="DOI" relationType="IsSupplementTo">10.1038/s41598-020-62118-4</relatedIdentifier>
</relatedIdentifiers>

Please see the schema at DataCite for all the fields and options allowed.

**Comment by arcadiafalcone** [comment]
Closed via #52.
