### ISSUE TITLE
DataCite: add support for ROR and GRID identifiers for affiliations

### ISSUE THREAD

**Issue by amyehodge** [sul-metadata/stanford-library-metadata#50]
This was added in version 4.3 of the DataCite metadata schema.

**Comment by amyehodge** [comment]
ROR is a priority over GRID

**Comment by arcadiafalcone** [comment]
@amyehodge How do the affiliationIdentifier entries look for Researcher 1 in the attached template? MODS has only one affiliation field, so whether the value is a string or a URI it gets mapped to mods/name/affiliation. If an affiliation schema is entered, it maps to DataCite affiliationIdentifier; if not, it maps to DataCite affiliation.

[datacite_template_20200413.xlsx](https://github.com/sul-metadata/stanford-library-metadata/files/4472037/datacite_template_20200413.xlsx)

**Comment by arcadiafalcone** [comment]
Looks like I forgot to increment the numbers in some of the labels, but hopefully it's enough for you to get the idea.

**Comment by amyehodge** [comment]
If affiliationIdentifier is used, then affiliationIdentifierScheme is required. Based on the format, you could likely derive affiliationIdentifierScheme from affiliationIdentifier, but you have affiliationIdentifier as a DO NOT EDIT field, while affiliationIdentifierScheme is editable. Seems like it should be the other way around, unless I'm misunderstanding the documentation. And there is no SchemeURI fields -- though maybe that's what you intend for affiliationIdentifierScheme since it says (if URI) above it?

The mapping you describe above makes sense. Does it handle the multiple affiliations okay? Is that going to be weird if there are 2 affiliations and one has an affiliationIdentifier and the other just affiliation (so one is a URI or code and the other is free text)?

**Comment by arcadiafalcone** [comment]
Closed via #52.
