### ISSUE TITLE
DataCite: role validation range shifts 

### ISSUE THREAD

**Issue by amyehodge** [sul-metadata/stanford-library-metadata#60]
For the author roles, it looks like the range for the field validation shifts as you move down the sheet, so that you lose one option at the top of the roles list for every row you move down. I was able to update this for my purposes, but just wanted to let you know. It appears to be an issue for the role field associated with every author — at least for the 11 authors I had for these 9 items.

I could clearly see that the first row had the range set for =role!$A2:$A52, and the second for =role!$A3:$A53, the third for =role!$A4:$A54, etc

**Comment by arcadiafalcone** [comment]
Closed by #72
