### ISSUE TITLE
DataCite: contributor MD is failing

### ISSUE THREAD

**Issue by amyehodge** [sul-metadata/stanford-library-metadata#62]
For participating institution, the metadata is now missing a required field. I can add this in manually for now to the converted xml but would be nice to reinstate.

The attribute ‘contributorType’ is required but missing. at line 88, column 0

Original metadata was fine:
![Screen Shot 2020-05-08 at 9 20 26 AM](https://user-images.githubusercontent.com/5558511/81426212-bbd32200-910d-11ea-9796-589c35c3113f.png)

Trying to updates I am now getting this:
<img width="829" alt="Screen Shot 2020-05-08 at 9 24 05 AM" src="https://user-images.githubusercontent.com/5558511/81426224-bfff3f80-910d-11ea-92be-390bebd18ec6.png">

**Comment by amyehodge** [comment]
Oops, the metadata examples didn't come through

Original metadata:
![Screen Shot 2020-05-08 at 9 20 26 AM](https://user-images.githubusercontent.com/5558511/81426113-98a87280-910d-11ea-8383-fa10472a2e2f.png)

Update:
<img width="829" alt="Screen Shot 2020-05-08 at 9 24 05 AM" src="https://user-images.githubusercontent.com/5558511/81426181-afe76000-910d-11ea-8216-2c53a7b6aeff.png">

**Comment by arcadiafalcone** [comment]
Closed by #72
